# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170306_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_text',
            field=models.CharField(max_length=200),
        ),
    ]
