# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170306_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question_text',
            new_name='question_text',
        ),
    ]
